version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_taxi_api
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: taxi_api
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  taxi-api:
    build: .
    container_name: taxi_api_app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/taxi_api
      - spring.datasource.username=root
      - spring.datasource.password=password
      - spring.jpa.hibernate.ddl-auto=update